name: QwenVoice
options:
  bundleIdPrefix: com.qwenvoice
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"

targets:
  QwenVoice:
    type: application
    platform: macOS
    sources:
      - QwenVoice
    resources:
      - path: QwenVoice/Resources
        buildPhase: resources
      - path: QwenVoice/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.qwenvoice.app
        PRODUCT_NAME: Qwen Voice
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: QwenVoice/Info.plist
        CODE_SIGN_ENTITLEMENTS: QwenVoice/QwenVoice.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
    dependencies:
      - package: GRDB

  QwenVoiceUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - QwenVoiceUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.qwenvoice.uitests
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        TEST_TARGET_NAME: QwenVoice
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: QwenVoice
