#!/usr/bin/env bash
# scripts/clean_build_caches.sh — free disk space by removing build
# artifacts that are safe to regenerate.
#
# Default mode removes "always-safe" items only:
#   - build/Vocello-macos26.dmg + release logs/metadata (regenerated by ./scripts/release.sh)
#   - the legacy build/Debug + build/Release split + retired harness leftovers
#
# --aggressive additionally wipes build/DerivedData + build/foundation (the
# next build is slower while those rebuild).
#
# Always preserved by default: build/DerivedData + build/foundation (incremental
# caches) and build/Vocello.app (the live build).
#
# Use this on the 8 GB dev machine where build/ balloons to 20+ GB
# during active iteration. The repo's .gitignore already excludes
# build/, so nothing removed here is version-controlled.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$REPO_ROOT/build"

aggressive=false
dry_run=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --aggressive) aggressive=true; shift ;;
        --dry-run|-n) dry_run=true; shift ;;
        -h|--help)
            cat <<'EOF'
Usage: clean_build_caches.sh [--aggressive] [--dry-run|-n]

  --aggressive  Also remove leftover harness DerivedData and foundation
                release derived-data (~11 GB extra). Next release.sh runs
                will be slower.
  --dry-run, -n Print what would be removed without removing it.
  -h, --help    Show this help.

Default removes only "always-safe" categories. See header in
scripts/clean_build_caches.sh for the full list and rationale.
EOF
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

remove_path() {
    local target="$1"
    if [[ ! -e "$target" ]]; then
        return 0
    fi
    if $dry_run; then
        echo "would-remove: $target"
    else
        rm -rf "$target"
        echo "removed: $target"
    fi
}

cd "$REPO_ROOT"

echo "==> Cleaning always-safe build artifacts ..."

# Release outputs (regenerated by release.sh).
remove_path "$BUILD_DIR/Vocello-macos26.dmg"
remove_path "$BUILD_DIR/release-build-settings.log"
remove_path "$BUILD_DIR/release-metadata.txt"
remove_path "$BUILD_DIR/xcodebuild-release.log"

# Legacy dual-folder split + retired harness leftovers.
remove_path "$BUILD_DIR/Debug"
remove_path "$BUILD_DIR/Release"
remove_path "$BUILD_DIR/uitest"
remove_path "$BUILD_DIR/audio-qc"
remove_path "$BUILD_DIR/instruments-traces"
remove_path "$BUILD_DIR/ui-bench"
remove_path "$BUILD_DIR/harness"

if $aggressive; then
    echo "==> --aggressive: also wiping DerivedData + foundation caches (~slower next build) ..."
    remove_path "$BUILD_DIR/DerivedData"
    remove_path "$BUILD_DIR/foundation"
fi

echo "==> Done."
if $dry_run; then
    echo "    (dry-run; no files removed)"
fi

if [[ -d "$BUILD_DIR" ]]; then
    echo "==> build/ size after cleanup:"
    du -sh "$BUILD_DIR" 2>/dev/null || true
fi
